---
title: "About"
date: "2024-08-14"
output: html_document
---


### Who ? 

Born and raised in Southern Ontario and spent a lot of my childhood marveling at the biodiversity in and around the Great Lakes region. I've always had a deep love for nature and a passion to protect it. That passion is what brought me to pursue a BSc in Biology at McMaster University (Class of 2018), an MSc in Conservation Biology at the University of Alberta (Class of 2021), and work as a public servant with the Canadian Wildlife Service (2022-2024). 

### What ? 

### How ? 

### Why ? 


### Fun Facts 
 * Favorite work-related activities: Coding (R is my preferred language) & Writing
 * Favorite non-work related activities: Hiking, crochet, and spending time with family & friends
 * Something I try to practice everyday: Sustainable living & gratitude
 * Alumna of both McMaster University (Class of 2018) & University of Alberta (Class of 2021)
 
 
 
### Overarching Goal

### What I Want to be known for
In the short term... 

In the long term...

### What, How, & Why of my work

### What makes me unique

### My Triangle Philosphy



